### ISSUE TITLE
Cannot set the API field's label separately than API field's ID/variable name?

### ISSUE THREAD

**Issue by armyofda12mnkeys** [HelloFax/hellosign-java-sdk#27] opened 2016-11-09 16:30 UTC
Another issue related to how im doing my Editable + Prefilled settings ... 
I cannot set the label separately than the API ID variable name. 
The java SDK complains (so i can't have something like 'Enter your Full Name' as the label text and '___patient_fullname___' as the API ID name):
http://www.screencast.com/t/YFqSBL0Gq

Does that seem wrong? If i make both the label and the variable name the same '___patient_fullname___', then the API doesn't complain.

**Comment by cmpaul** [comment] 2016-11-18 18:53
@armyofda12mnkeys Sorry for the delay on this, just watched your screencast and the problem is that we don't currently *use* the API ID for the custom field "name". In fact, the API ID isn't used for anything other than mapping data to fields once you receive the completed request. 

This is a limitation of our API, not the Java SDK. Your assumption that you can use the API ID is totally justified and I think it _should_ work that way. Let me file a ticket with our API team and see if we can get this figured out.

**Comment by armyofda12mnkeys** [comment] 2016-11-18 19:46
Thanks, let me know what they say!

**Comment by codylerum** [comment] 2016-12-07 18:30
@cmpaul Also running into this. 

The API docs say to use

TemplateSignatureRequest#setCustomFieldValue(String name, String value)

However I cannot figure out what the "name" would be in this case. It doesn't appear to be API ID or Label and those are the only two that I'm seeing in the template editor.

**Comment by armyofda12mnkeys** [comment] 2016-12-07 18:59
Hey @codylerum,
This response from Hellosign to me from last week may help:
I think they basically say use the Name and not the API ID 
(which is a bit weird, since says optional in the admin UI.
The consequence of that, is you may actually want to use a placeholder label in this 'optional' field like 'Enter your First Name' in case the user removes the prefilled data (if the field is editable textfield).
Then they will see the label text. I guess nothing should be referring to the API ID in your java code, and just the name.


> Hi ###,
> 
> I saw that issue, and he's right - the addCustomField setName() and setCustomFieldValue param are both looking for the Field Label string - not the API ID. 
> The API ID is only used to map data to each specific field, unlike the Field Labels, which can be shared (for instance: if you have a spot for "Customer Full Name" on your form eight times, you'd place eight me (when sending) text boxes, each with the Field Label Customer Full Name on the template itself, but you'd only include one request.setCustomFieldValue("Customer Full Name", "Bob The Signer"); or x.setName("Customer Full Name");instead of 8 different times for each instance of the field, which you'd be forced to do if we mapped to API IDs).
> 
> 
> 
> NOTE - further clarification: The popup note in HelloSign is warning you that you can extract the information returned BACK to you from the HelloSign API for that specific field.That's what it means when it says "... making calls from our API."
> 
> 
> 
> NOTE - I AGREE THAT THIS IS A TOTALLY CLUMSY WAY TO PHRASE THE PURPOSE OF THE API ID WHEN CREATING TEMPLATES. The documentation around custom fields isn't super clear. Check out our attempt in the API Documentation to explain that it's the Field Label that we're looking for: https://www.hellosign.com/api/templatesAndApiWalkthrough - also, see attachment
> 
> Also, note that it's the Field Label that's shown to the signer - not the API ID.
> 
> So for issue 26, pass the Field Label and not the API ID in your x.setName(); line and you'll be ready to rock.

**Comment by codylerum** [comment] 2016-12-08 00:44
@armyofda12mnkeys I wan't setting the field to Me (at Signing) which is required. The labeling of those fields is a little weird when using the API though I don't have a good suggestion either 😃

**Comment by cmpaul** [comment] 2016-12-08 17:07
@codylerum Glad you got it working and thanks for the feedback.

@armyofda12mnkeys is correct and "Name" == field label. We're working on plumbing the API ID for the purpose of custom field value assignment and hope to have that out soon.

In the meantime, I agree that Java SDK documentation and naming of those parameters could be clearer. I'll make a point to update those (or feel free to submit a Pull Request!).

**Comment by mveitas** [comment] 2017-02-24 14:34
@cmpaul Do you have a timeline for using the API ID values with custom field value assignment?

**Comment by cmpaul** [comment] 2017-02-24 19:40
@mveitas I don't, but I'd really like to get that in. Let me discuss with our product team and find out.

**Comment by cmpaul** [comment] 2017-02-28 18:42
@mveitas Good news, I have this patched and ready for our next software update which should land in the next 2 weeks as part of our scheduled release cycle. Also, be sure to subscribe to our status page (https://status.hellosign.com) to be notified of scheduled updates.

**Comment by armyofda12mnkeys** [comment] 2017-02-28 20:25
Does that mean I can leave the 'label' blank (or "Enter your first name") in the Hellosign UI interface and have my api_id called ___patient_firstname___ ... and then do request.setCustomFieldValue ("___patient_firstname___", "John"); without the api complaining that the 'key' isn't correct?

So I think the expected results for two cases I'm talking about above:
1. if set a blank Label in the Admin UI (and my api_id is ___patient_firstname___ pretend), then will show nothing in the textfield if i do pretend request.setCustomFieldValue ("___patient_firstname___", ""); 
and not complain about "___patient_firstname___" like how it did before.

2. if using a non-blank Label in the Admin UI like "Enter your first name" (and my api_id is ___patient_firstname___ pretend), then 
  a. that will show up initially if the field is not prefilled pretend if i did request.setCustomFieldValue ("___patient_firstname___", "");
  b. and will not show up if the field is prefilled with  request.setCustomFieldValue ("___patient_firstname___", "John");

**Comment by cmpaul** [comment] 2017-02-28 20:30
@armyofda12mnkeys 

No, you'll need a "Field Label" (it's required) and it's displayed to the signer when they view the document. However, you're correct that after the change is deployed, you will be able to do what you describe with the api_id.

**Comment by armyofda12mnkeys** [comment] 2017-02-28 20:54
K sounds good, having a Label as required is fine by me.

Pretend then the Label for a textfield is "Enter your first name" and the api_id is patient_firstname... I just need to do:
request.setCustomFieldValue ("patient_firstname", "John");
or will there be a new method?
request.setCustomFieldAPIValue ("patient_firstname", "John");
I'm curious, as maybe you have previous customers that depended on using the Label name in the SDK vs the nicer api_id that we prefer.

**Comment by cmpaul** [comment] 2017-02-28 21:14
@armyofda12mnkeys Correct, the `name` ("Field Label") and the `api_id` will be interchangeable for that parameter. :D

**Comment by armyofda12mnkeys** [comment] 2017-03-01 17:22
Your solution is perfect. Will keep an eye on this thread as we'll probably roll this feature out as soon as you can make it. Thanks @cmpaul !!!

**Comment by cmpaul** [comment] 2017-03-17 17:46
@armyofda12mnkeys This is live now. Please give this a try and let me know how it works for you.

**Comment by armyofda12mnkeys** [comment] 2017-03-17 19:28
@cmpaul cool it worked as seen in pic below...
Btw I didn't need to update the hellosign-3.5.6.jar file. Was this change done from the Hellosign's api side or Hellosign's java sdk side? I'm guessing former?
![image](https://cloud.githubusercontent.com/assets/410112/24059637/30843ac4-0b26-11e7-849f-7533edcb7c6e.png)

**Comment by cmpaul** [comment] 2017-03-17 20:01
Yep, you're correct, it was the API side. :)

Glad to hear this is working, I'm going to close this issue.

**Closed by cmpaul** 2017-03-17 20:01 UTC
Labels: enhancement

**Comment by Dilip12344** [comment] 2018-06-28 10:34
Ho to add implement Radio button,
let suppose i have Gender and two radio button/checkbox. user must select only one among both, then how do i implement.
i have seen "Grouping Checkboxes" but how to use in java code
