### ISSUE TITLE
GetEmbeddedTemplateEditUrl with skipSignerRoles and skipSubjectMessage true

### ISSUE THREAD

**Issue by mashleyttu** [HelloFax/hellosign-java-sdk#32] opened 2016-12-19 22:11 UTC
Hi,

HelloSignClient#getEmbeddedTemplateEditUrl(String templateId, boolean skipSignerRoles, boolean skipSubjectMessage); with both skipSignerRoles and skipSubjectMessage set to true doesn't seem to work. Using version 3.5.6. Should there be an & in the query parameters if both are true?

Currently running this as workaround: 

public String getTemplateEditUrl(String templateId) throws HelloSignException {
		EmbeddedResponse ep = client.getEmbeddedTemplateEditUrl(templateId);
		return ep.getEditUrl().replace("&force_signer_input=1&force_edit_subject_message=1",
				"&skip_signer_roles=1&skip_subject_message=1");
	}

Thanks,
Matt

**Comment by cmpaul** [comment] 2016-12-30 00:06
@mashleyttu Sounds like a bug! I'll schedule this for patching in the next update.

**Comment by cmpaul** [comment] 2017-02-23 20:58
Hi @mashleyttu , apologies for the delay on this. We've identified the root cause of this bug and will be releasing a fix for it in an upcoming software update in the next few weeks.

In the meantime, you can tweak your work-around to simply remove the `force_*` URL parameters. The presence of those forces the signer and message prompts to display. Removing them will prevent them from being shown.

**Comment by cmpaul** [comment] 2017-02-23 20:58
I'm going to close this ticket, as this is an issue on the HelloSign API side of things.

**Closed by cmpaul** 2017-02-23 20:58 UTC
Labels: bug
